
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudiant
spec:
  selector:
    matchLabels:
      app: etudiant
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: etudiant
    spec:
      containers:
      - name: etudiant
        image: ouattara/etudiant:latest
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: prod
---

apiVersion: v1
kind: Service
metadata:
  name: etudiant

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: etudiant

  ports:
    - name: http
      port: 8080
      nodePort: 30080

  type: NodePort
